print("hay tao nhan vat!")
name=input("nhan vat cua ban ten gi")
age=input("nhan vat cua ban bao nhieu tuoi")
strenghts=input("nhan vat cua ban co suc manh gi")
weaknesses=input("nhan vat cua ban co diem yeu gi?")
print("nhan vat cua ban ten la",name)
print("nhan vat cua ban",age,"tuoi")
print("suc manh:",strenghts)
print("diem yeu:",weaknesses)
print(name,"noi'cam on vi da tao ra to!'")
